<?php


namespace App\Repository;


use App\Service\QueryService;

class GeneralRepository extends QueryService
{

    public function getOne($param)
    {
        return parent::getOne($param); // TODO: Change the autogenerated stub
    }
}